export type CountryAlpha3ISOCode =
  | 'ABW'
  | 'AFG'
  | 'AGO'
  | 'AIA'
  | 'ALA'
  | 'ALB'
  | 'AND'
  | 'ARE'
  | 'ARG'
  | 'ARM'
  | 'ASM'
  | 'ATA'
  | 'ATF'
  | 'ATG'
  | 'AUS'
  | 'AUT'
  | 'AZE'
  | 'BDI'
  | 'BEL'
  | 'BEN'
  | 'BES'
  | 'BFA'
  | 'BGD'
  | 'BGR'
  | 'BHR'
  | 'BHS'
  | 'BIH'
  | 'BLM'
  | 'BLR'
  | 'BLZ'
  | 'BMU'
  | 'BOL'
  | 'BRA'
  | 'BRB'
  | 'BRN'
  | 'BTN'
  | 'BVT'
  | 'BWA'
  | 'CAF'
  | 'CAN'
  | 'CCK'
  | 'CHE'
  | 'CHL'
  | 'CHN'
  | 'CIV'
  | 'CMR'
  | 'COD'
  | 'COG'
  | 'COK'
  | 'COL'
  | 'COM'
  | 'CPV'
  | 'CRI'
  | 'CUB'
  | 'CUW'
  | 'CXR'
  | 'CYM'
  | 'CYP'
  | 'CZE'
  | 'DEU'
  | 'DJI'
  | 'DMA'
  | 'DNK'
  | 'DOM'
  | 'DZA'
  | 'ECU'
  | 'EGY'
  | 'ERI'
  | 'ESH'
  | 'ESP'
  | 'EST'
  | 'ETH'
  | 'FIN'
  | 'FJI'
  | 'FLK'
  | 'FRA'
  | 'FRO'
  | 'FSM'
  | 'GAB'
  | 'GBR'
  | 'GEO'
  | 'GGY'
  | 'GHA'
  | 'GIB'
  | 'GIN'
  | 'GLP'
  | 'GMB'
  | 'GNB'
  | 'GNQ'
  | 'GRC'
  | 'GRD'
  | 'GRL'
  | 'GTM'
  | 'GUF'
  | 'GUM'
  | 'GUY'
  | 'HKG'
  | 'HMD'
  | 'HND'
  | 'HRV'
  | 'HTI'
  | 'HUN'
  | 'IDN'
  | 'IMN'
  | 'IND'
  | 'IOT'
  | 'IRL'
  | 'IRN'
  | 'IRQ'
  | 'ISL'
  | 'ISR'
  | 'ITA'
  | 'JAM'
  | 'JEY'
  | 'JOR'
  | 'JPN'
  | 'KAZ'
  | 'KEN'
  | 'KGZ'
  | 'KHM'
  | 'KIR'
  | 'KNA'
  | 'KOR'
  | 'KWT'
  | 'LAO'
  | 'LBN'
  | 'LBR'
  | 'LBY'
  | 'LCA'
  | 'LIE'
  | 'LKA'
  | 'LSO'
  | 'LTU'
  | 'LUX'
  | 'LVA'
  | 'MAC'
  | 'MAF'
  | 'MAR'
  | 'MCO'
  | 'MDA'
  | 'MDG'
  | 'MDV'
  | 'MEX'
  | 'MHL'
  | 'MKD'
  | 'MLI'
  | 'MLT'
  | 'MMR'
  | 'MNE'
  | 'MNG'
  | 'MNP'
  | 'MOZ'
  | 'MRT'
  | 'MSR'
  | 'MTQ'
  | 'MUS'
  | 'MWI'
  | 'MYS'
  | 'MYT'
  | 'NAM'
  | 'NCL'
  | 'NER'
  | 'NFK'
  | 'NGA'
  | 'NIC'
  | 'NIU'
  | 'NLD'
  | 'NOR'
  | 'NPL'
  | 'NRU'
  | 'NZL'
  | 'OMN'
  | 'PAK'
  | 'PAN'
  | 'PCN'
  | 'PER'
  | 'PHL'
  | 'PLW'
  | 'PNG'
  | 'POL'
  | 'PRI'
  | 'PRK'
  | 'PRT'
  | 'PRY'
  | 'PSE'
  | 'PYF'
  | 'QAT'
  | 'REU'
  | 'ROU'
  | 'RUS'
  | 'RWA'
  | 'SAU'
  | 'SDN'
  | 'SEN'
  | 'SGP'
  | 'SGS'
  | 'SHN'
  | 'SJM'
  | 'SLB'
  | 'SLE'
  | 'SLV'
  | 'SMR'
  | 'SOM'
  | 'SPM'
  | 'SRB'
  | 'SSD'
  | 'STP'
  | 'SUR'
  | 'SVK'
  | 'SVN'
  | 'SWE'
  | 'SWZ'
  | 'SXM'
  | 'SYC'
  | 'SYR'
  | 'TCA'
  | 'TCD'
  | 'TGO'
  | 'THA'
  | 'TJK'
  | 'TKL'
  | 'TKM'
  | 'TLS'
  | 'TON'
  | 'TTO'
  | 'TUN'
  | 'TUR'
  | 'TUV'
  | 'TWN'
  | 'TZA'
  | 'UGA'
  | 'UKR'
  | 'UMI'
  | 'URY'
  | 'USA'
  | 'UZB'
  | 'VAT'
  | 'VCT'
  | 'VEN'
  | 'VGB'
  | 'VIR'
  | 'VNM'
  | 'VUT'
  | 'WLF'
  | 'WSM'
  | 'YEM'
  | 'ZAF'
  | 'ZMB'
  | 'ZWE'

export type CountryISOCode =
  | 'US'
  | 'CH'
  | 'BR'
  | 'CA'
  | 'CN'
  | 'IE'
  | 'GB'
  | 'NL'
  | 'BM'
  | 'LU'
  | 'CL'
  | 'KY'
  | 'SE'
  | 'MX'
  | 'UY'
  | 'TW'
  | 'ZA'
  | 'CO'
  | 'IN'
  | 'AR'
  | 'AU'
  | 'ES'
  | 'PA'
  | 'BE'
  | 'PE'
  | 'JP'
  | 'DE'
  | 'IL'
  | 'HK'
  | 'MC'
  | 'FR'
  | 'SG'
  | 'GR'
  | 'IT'
  | 'NO'
  | 'KR'
  | 'RU'
  | 'FI'
  | 'DK'
  | 'PH'
  | 'AE'
  | 'TR'
  | 'ID'
  | 'JE'
  | 'CY'
  | 'MO'
  | 'BS'
  | 'CR'
  | 'KZ'
  | 'MT'
  | 'JO'
  | 'NZ'
  | 'VG'
  | 'MY'
  | 'HU'
  | 'AT'
  | 'MU'
  | 'DO'
  | 'MZ'
  | 'AZ'
  | 'TH'
  | 'GG'
  | 'CZ'
  | 'BZ'
  | 'PT'
  | 'LB'
  | 'OM'
  | 'PG'
  | 'GI'
  | 'IM'
  | 'SK'
  | 'EG'
  | 'NG'
  | 'PL'
  | 'MK'
  | 'AI'
  | 'RO'
  | 'GH'
  | 'RS'
  | 'LT'
  | 'BN'
  | 'GE'
  | 'AN'
  | 'TZ'
  | 'MD'
  | 'MA'
  | 'UA'
  | 'MN'
  | 'MH'
  | 'ME'
  | 'MG'
  | 'KH'
  | 'IS'
  | 'BB'
  | 'NA'
  | 'VN'
  | 'LI'
  | 'ZM'
  | 'FK'
  | 'EE'
  | 'KG'
  | 'BG'
  | 'SI'
  | 'BD'
  | 'GA'
  | 'LV'
  | 'MM'
  | 'CI'
  | 'SN'
  | 'GL'
  | 'BF'
  | 'BH'
  | 'QA'
  | 'KE'
  | 'PK'
  | 'RE'
  | 'HR'
  | 'LK'

type EHDAvailableGovernmentBondCountryCode =
  | 'AU'
  | 'BR'
  | 'CA'
  | 'CN'
  | 'DE'
  | 'ES'
  | 'FR'
  | 'GR'
  | 'IN'
  | 'IT'
  | 'JP'
  | 'MX'
  | 'NL'
  | 'NZ'
  | 'PT'
  | 'RU'
  | 'SW'
  | 'UK'
  | 'US'

export type EHDBondPeriod = '1M' | '3M' | '6M' | '1Y' | '3Y' | '5Y' | '10Y'

export type EHDBulkDataType = 'eod' | 'splits' | 'dividends'

export type EHDBulkExchangeCode =
  | EHDExchangeCode
  | 'NYSE'
  | 'NASDAQ'
  | 'BATS'
  | 'AMEX'

export type EHDCurrencyCode =
  | 'USD'
  | 'EUR'
  | 'AUD'
  | 'GBP'
  | 'HRK'
  | 'PHP'
  | 'INR'
  | 'BRL'
  | 'DKK'
  | 'MYR'
  | 'SGD'
  | 'CZK'
  | 'HUF'
  | 'PLN'
  | 'THB'
  | 'TRY'
  | 'CNY'
  | 'CAD'
  | 'HKD'
  | 'RUB'
  | 'ZAR'
  | 'IDR'
  | 'JPY'
  | 'KRW'
  | 'PKR'
  | 'TWD'
  | 'MXN'
  | 'NZD'
  | 'NOK'
  | 'SEK'
  | 'CHF'
  | 'ILS'
  | 'SAR'

export type EHDCalendarDataTypeName = 'IPOs' | 'Splits' | 'Trends' | 'Earnings'

export type EHDCurrencyName =
  | 'US Dollar'
  | 'Euro'
  | 'Australian Dollar'
  | 'British Pound'
  | 'Croatian kuna'
  | 'Philippine peso'
  | 'Indian Rupee'
  | 'Brazilian real'
  | 'Danish krone'
  | 'Malaysian Ringgit'
  | 'Singapore Dollar'
  | 'Hungarian forin'
  | 'Polish złoty'
  | 'Thai baht'
  | 'Turkish lira'
  | 'Renminbi'
  | 'Canadian Dollar'
  | 'Hong Kong Dollar'
  | 'Russian Rouble'
  | 'South African Rand'
  | 'Indonesian Rupiah'
  | 'Japanese Yen'
  | 'Korean Won'
  | 'Pakistani rupee'
  | 'New Taiwan Dollar'
  | 'Mexican Peso'
  | 'New Zealand Dollar'
  | 'Norwegian Krone'
  | 'Swedish krone'
  | 'Swiss Franc'
  | 'Israeli new shekel'
  | 'Saudi riyal'

export type EHDCurrencySymbol =
  | '$'
  | '€'
  | 'A$'
  | '£'
  | 'kn'
  | '₱'
  | 'INR'
  | 'R$'
  | 'kr'
  | 'RM'
  | 'S$'
  | 'null'
  | 'Ft'
  | 'zł'
  | '฿'
  | '₺'
  | '¥'
  | 'C$'
  | 'HK$'
  | '₽'
  | 'R'
  | 'Rp'
  | '₩'
  | '₨'
  | 'NT$'
  | 'NZ$'
  | 'CHF'
  | '₪'
  | 'SR'

export type EHDCouponPaymentFrequency = 'Semi-Annual' | 'Annual'

export type EHDECBAvailableCurrency = 'GBP' | 'JPY' | 'USD' | 'NOK' | 'SEK'

export type EHDEURIBORPeriod = '1W' | '1M' | '3M' | '6M' | '12M'

export type EHDETFCategory =
  | 'Africa &amp; Middle East Equity'
  | 'Africa Equity'
  | 'Alt - Currency'
  | 'Alt - Other'
  | 'Alt - Relative Value Arbitrage'
  | 'Asia Bond'
  | 'Asia Bond - Local Currency'
  | 'Asia ex-Japan Equity'
  | 'Asia ex-Japan Small/Mid-Cap Equity'
  | 'Asia-Pacific Equity'
  | 'Asia-Pacific ex-Japan Equity'
  | 'Australia &amp; New Zealand Equity'
  | 'Brazil Equity'
  | 'BRIC Equity'
  | 'Canada Equity'
  | 'China Equity'
  | 'China Equity - A Shares'
  | 'Commodities - Broad Agriculture'
  | 'Commodities - Broad Basket'
  | 'Commodities - Energy'
  | 'Commodities - Grains'
  | 'Commodities - Industrial &amp; Broad Metals'
  | 'Commodities - Livestock'
  | 'Commodities - Precious Metals'
  | 'Commodities - Softs'
  | 'Convertible Bond - Global'
  | 'Corporate Bond'
  | 'Emerging Europe Equity'
  | 'Emerging Europe ex-Russia Equity'
  | 'EUR Bond - Long Term'
  | 'EUR Corporate Bond'
  | 'EUR Corporate Bond - Short Term'
  | 'EUR Diversified Bond'
  | 'EUR Flexible Bond'
  | 'EUR Government Bond'
  | 'EUR Government Bond - Short Term'
  | 'EUR High Yield Bond'
  | 'EUR Inflation-Linked Bond'
  | 'EUR Subordinated Bond'
  | 'EUR Ultra Short-Term Bond'
  | 'Europe Equity Income'
  | 'Europe ex-UK Equity'
  | 'Europe Flex-Cap Equity'
  | 'Europe Large-Cap Blend Equity'
  | 'Europe Large-Cap Growth Equity'
  | 'Europe Large-Cap Value Equity'
  | 'Europe Mid-Cap Equity'
  | 'Europe Small-Cap Equity'
  | 'Eurozone Flex-Cap Equity'
  | 'Eurozone Large-Cap Equity'
  | 'Eurozone Mid-Cap Equity'
  | 'Eurozone Small-Cap Equity'
  | 'France Equity'
  | 'GBP Corporate Bond'
  | 'GBP Corporate Bond - Short Term'
  | 'GBP Diversified Bond - Short Term'
  | 'GBP Government Bond'
  | 'GBP Inflation-Linked Bond'
  | 'GBP Moderate Allocation'
  | 'GBP Moderately Adventurous Allocation'
  | 'GBP Moderately Cautious Allocation'
  | 'Germany Equity'
  | 'Germany Small/Mid-Cap Equity'
  | 'Global Bond'
  | 'Global Bond - EUR Hedged'
  | 'Global Bond - GBP Hedged'
  | 'Global Bond - USD Hedged'
  | 'Global Corporate Bond'
  | 'Global Corporate Bond - GBP Hedged'
  | 'Global Corporate Bond - USD Hedged'
  | 'Global Emerging Markets Bond'
  | 'Global Emerging Markets Bond - EUR Biased'
  | 'Global Emerging Markets Bond - Local Currency'
  | 'Global Emerging Markets Corporate Bond'
  | 'Global Emerging Markets Equity'
  | 'Global Emerging Markets Small/Mid-Cap Equity'
  | 'Global Equity Income'
  | 'Global Flex-Cap Equity'
  | 'Global Frontier Markets Equity'
  | 'Global High Yield Bond'
  | 'Global High Yield Bond - EUR Hedged'
  | 'Global High Yield Bond - GBP Hedged'
  | 'Global Inflation-Linked Bond'
  | 'Global Inflation-Linked Bond - EUR Hedged'
  | 'Global Inflation-Linked Bond - GBP Hedged'
  | 'Global Inflation-Linked Bond - USD Hedged'
  | 'Global Large-Cap Blend Equity'
  | 'Global Large-Cap Growth Equity'
  | 'Global Large-Cap Value Equity'
  | 'Global Small/Mid-Cap Equity'
  | 'India Equity'
  | 'Indonesia Equity'
  | 'Islamic Equity - Other'
  | 'Islamic Global Equity'
  | 'Israel Large/Mid-Cap Equity'
  | 'Italy Equity'
  | 'Japan Large-Cap Equity'
  | 'Japan Small/Mid-Cap Equity'
  | 'Korea Equity'
  | 'Latin America Equity'
  | 'Money Market - Other'
  | 'Netherlands Equity'
  | 'Nordic Equity'
  | 'Other'
  | 'Other Bond'
  | 'Other Equity'
  | 'Pacific ex-Japan Equity'
  | 'Poland Equity'
  | 'Property - Indirect Asia'
  | 'Property - Indirect Europe'
  | 'Property - Indirect Global'
  | 'Property - Indirect North America'
  | 'Property - Indirect Other'
  | 'RMB Bond - Onshore'
  | 'Russia Equity'
  | 'Sector Equity Agriculture'
  | 'Sector Equity Alternative Energy'
  | 'Sector Equity Biotechnology'
  | 'Sector Equity Communications'
  | 'Sector Equity Consumer Goods &amp; Services'
  | 'Sector Equity Ecology'
  | 'Sector Equity Energy'
  | 'Sector Equity Financial Services'
  | 'Sector Equity Healthcare'
  | 'Sector Equity Industrial Materials'
  | 'Sector Equity Infrastructure'
  | 'Sector Equity Natural Resources'
  | 'Sector Equity Precious Metals'
  | 'Sector Equity Private Equity'
  | 'Sector Equity Technology'
  | 'Sector Equity Utilities'
  | 'Sector Equity Water'
  | 'South Africa &amp; Namibia Equity'
  | 'Spain Equity'
  | 'Sweden Equity'
  | 'Switzerland Equity'
  | 'Taiwan Large-Cap Equity'
  | 'Thailand Equity'
  | 'Trading - Leveraged/Inverse Commodities'
  | 'Trading - Leveraged/Inverse Equity'
  | 'Trading - Leveraged/Inverse Fixed Income'
  | 'Trading - Leveraged/Inverse Other'
  | 'Turkey Equity'
  | 'UK Equity Income'
  | 'UK Flex-Cap Equity'
  | 'UK Large-Cap Equity'
  | 'UK Mid-Cap Equity'
  | 'UK Small-Cap Equity'
  | 'US Large-Cap Blend Equity'
  | 'US Large-Cap Growth Equity'
  | 'US Large-Cap Value Equity'
  | 'US Mid-Cap Equity'
  | 'US Small-Cap Equity'
  | 'USD Corporate Bond'
  | 'USD Diversified Bond'
  | 'USD Diversified Bond - Short Term'
  | 'USD Government Bond'
  | 'USD High Yield Bond'
  | 'USD Inflation-Linked Bond'
  | 'USD Moderate Allocation'
  | 'Vietnam Equity'

export type EHDExchangeCode =
  | 'AS'
  | 'AT'
  | 'AU'
  | 'BA'
  | 'BE'
  | 'BK'
  | 'BOND'
  | 'BR'
  | 'BSE'
  | 'BUD'
  | 'CC'
  | 'CO'
  | 'COMM'
  | 'DU'
  | 'ETLX'
  | 'EUFUND'
  | 'F'
  | 'FOREX'
  | 'GBOND'
  | 'HA'
  | 'HE'
  | 'HK'
  | 'HM'
  | 'IC'
  | 'IL'
  | 'INDX'
  | 'IR'
  | 'IS'
  | 'JK'
  | 'JSE'
  | 'KAR'
  | 'KLSE'
  | 'KO'
  | 'KQ'
  | 'LIM'
  | 'LS'
  | 'LSE'
  | 'LU'
  | 'MC'
  | 'MCX'
  | 'MI'
  | 'MONEY'
  | 'MU'
  | 'MX'
  | 'NB'
  | 'NFN'
  | 'NSE'
  | 'OL'
  | 'PA'
  | 'PSE'
  | 'RG'
  | 'SA'
  | 'SG'
  | 'SHE'
  | 'SHG'
  | 'SN'
  | 'SR'
  | 'ST'
  | 'STU'
  | 'SW'
  | 'TA'
  | 'TO'
  | 'TW'
  | 'TWO'
  | 'US'
  | 'V'
  | 'VI'
  | 'VN'
  | 'VS'
  | 'VX'
  | 'WAR'
  | 'XETRA'
  | 'ZSE'

export type EHDFiscalYearEndMonth =
  | 'January'
  | 'February'
  | 'March'
  | 'April'
  | 'May'
  | 'June'
  | 'July'
  | 'August'
  | 'September'
  | 'October'
  | 'November'
  | 'December'

export type EHDHomeCategory = 'International' | 'Domestic'

export type EHDHolidayType = 'official' | 'bank'

export type EHDIndustry =
  | 'Industry'
  | 'Agricultural Chemicals'
  | 'Agricultural Inputs'
  | 'Aluminum'
  | 'Building Materials'
  | 'Chemicals'
  | 'Chemicals - Major Diversified'
  | 'Coal'
  | 'Coking Coal'
  | 'Copper'
  | 'Gold'
  | 'Independent Oil & Gas'
  | 'Industrial Metals & Minerals'
  | 'Lumber & Wood Production'
  | 'Major Integrated Oil & Gas'
  | 'Nonmetallic Mineral Mining'
  | 'Oil & Gas Drilling & Exploration'
  | 'Oil & Gas Equipment & Services'
  | 'Oil & Gas Pipelines'
  | 'Oil & Gas Refining & Marketing'
  | 'Other Industrial Metals & Mining'
  | 'Other Precious Metals & Mining'
  | 'Paper & Paper Products'
  | 'Silver'
  | 'Specialty Chemicals'
  | 'Steel'
  | 'Steel & Iron'
  | 'Synthetics'
  | 'Advertising Agencies'
  | 'Broadcasting'
  | 'Electronic Gaming & Multimedia'
  | 'Entertainment'
  | 'Internet Content & Information'
  | 'Pay TV'
  | 'Publishing'
  | 'Telecom Services'
  | 'Conglomerates'
  | 'Advertising Agencies'
  | 'Apparel Manufacturing'
  | 'Apparel Retail'
  | 'Apparel Stores'
  | 'Auto & Truck Dealerships'
  | 'Auto Manufacturers'
  | 'Auto Parts'
  | 'Broadcasting - Radio'
  | 'Broadcasting - TV'
  | 'Department Stores'
  | 'Footwear & Accessories'
  | 'Furnishings, Fixtures & Appliances'
  | 'Gambling'
  | 'Home Furnishings & Fixtures'
  | 'Home Improvement Retail'
  | 'Home Improvement Stores'
  | 'Internet Retail'
  | 'Leisure'
  | 'Lodging'
  | 'Luxury Goods'
  | 'Marketing Services'
  | 'Media - Diversified'
  | 'Packaging & Containers'
  | 'Personal Services'
  | 'Publishing'
  | 'Recreational Vehicles'
  | 'Residential Construction'
  | 'Resorts & Casinos'
  | 'Restaurants'
  | 'Rubber & Plastics'
  | 'Specialty Retail'
  | 'Textile Manufacturing'
  | 'Travel Services'
  | 'Beverages - Brewers'
  | 'Beverages - Soft Drinks'
  | 'Beverages - Wineries & Distilleries'
  | 'Beverages-Brewers'
  | 'Beverages-Non-Alcoholic'
  | 'Beverages-Wineries & Distilleries'
  | 'Confectioners'
  | 'Discount Stores'
  | 'Education & Training Services'
  | 'Farm Products'
  | 'Food Distribution'
  | 'Grocery Stores'
  | 'Household & Personal Products'
  | 'Packaged Foods'
  | 'Pharmaceutical Retailers'
  | 'Tobacco'
  | 'Appliances'
  | 'Auto Manufacturers - Major'
  | 'Auto Parts'
  | 'Beverages - Brewers'
  | 'Beverages - Soft Drinks'
  | 'Beverages - Wineries & Distillers'
  | 'Business Equipment'
  | 'Cigarettes'
  | 'Cleaning Products'
  | 'Confectioners'
  | 'Dairy Products'
  | 'Electronic Equipment'
  | 'Farm Products'
  | 'Food - Major Diversified'
  | 'Home Furnishings & Fixtures'
  | 'Housewares & Accessories'
  | 'Meat Products'
  | 'Office Supplies'
  | 'Packaging & Containers'
  | 'Paper & Paper Products'
  | 'Personal Products'
  | 'Photographic Equipment & Supplies'
  | 'Processed & Packaged Goods'
  | 'Recreational Goods, Other'
  | 'Recreational Vehicles'
  | 'REIT - Retail'
  | 'Rubber & Plastics'
  | 'Sporting Goods'
  | 'Textile - Apparel Clothing'
  | 'Textile - Apparel Footwear & Accessories'
  | 'Tobacco Products, Other'
  | 'Toys & Games'
  | 'Trucks & Other Vehicles'
  | 'Oil & Gas Drilling'
  | 'Oil & Gas E&P'
  | 'Oil & Gas Equipment & Services'
  | 'Oil & Gas Integrated'
  | 'Oil & Gas Midstream'
  | 'Oil & Gas Refining & Marketing'
  | 'Thermal Coal'
  | 'Uranium'
  | 'Accident & Health Insurance'
  | 'Asset Management'
  | 'Closed-End Fund - Debt'
  | 'Closed-End Fund - Equity'
  | 'Closed-End Fund - Foreign'
  | 'Credit Services'
  | 'Diversified Investments'
  | 'Foreign Money Center Banks'
  | 'Foreign Regional Banks'
  | 'Insurance Brokers'
  | 'Investment Brokerage - National'
  | 'Investment Brokerage - Regional'
  | 'Life Insurance'
  | 'Money Center Banks'
  | 'Mortgage Investment'
  | 'Property & Casualty Insurance'
  | 'Property Management'
  | 'Real Estate Development'
  | 'Regional - Mid-Atlantic Banks'
  | 'Regional - Midwest Banks'
  | 'Regional - Northeast Banks'
  | 'Regional - Pacific Banks'
  | 'Regional - Southeast Banks'
  | 'Regional - Southwest  Banks'
  | 'REIT - Diversified'
  | 'REIT - Healthcare Facilities'
  | 'REIT - Hotel/Motel'
  | 'REIT - Industrial'
  | 'REIT - Office'
  | 'REIT - Residential'
  | 'REIT - Retail'
  | 'Savings & Loans'
  | 'Surety & Title Insurance'
  | 'Asset Management'
  | 'Banks - Global'
  | 'Banks - Regional - Africa'
  | 'Banks - Regional - Asia'
  | 'Banks - Regional - Australia'
  | 'Banks - Regional - Canada'
  | 'Banks - Regional - Europe'
  | 'Banks - Regional - Latin America'
  | 'Banks - Regional - US'
  | 'Banks-Diversified'
  | 'Banks-Regional'
  | 'Capital Markets'
  | 'Credit Services'
  | 'Financial Conglomerates'
  | 'Financial Data & Stock Exchanges'
  | 'Financial Exchanges'
  | 'Insurance - Diversified'
  | 'Insurance - Life'
  | 'Insurance - Property & Casualty'
  | 'Insurance - Reinsurance'
  | 'Insurance - Specialty'
  | 'Insurance Brokers'
  | 'Insurance-Diversified'
  | 'Insurance-Life'
  | 'Insurance-Property & Casualty'
  | 'Insurance-Reinsurance'
  | 'Insurance-Specialty'
  | 'Mortgage Finance'
  | 'Savings & Cooperative Banks'
  | 'Shell Companies'
  | 'Specialty Finance'
  | 'Biotechnology'
  | 'Diagnostic Substances'
  | 'Diagnostics & Research'
  | 'Drug Delivery'
  | 'Drug Manufacturers - Major'
  | 'Drug Manufacturers - Other'
  | 'Drug Manufacturers - Specialty & Generic'
  | 'Drug Manufacturers-General'
  | 'Drug Manufacturers-Specialty & Generic'
  | 'Drug Related Products'
  | 'Drugs - Generic'
  | 'Health Care Plans'
  | 'Health Information Services'
  | 'Healthcare Plans'
  | 'Home Health Care'
  | 'Hospitals'
  | 'Long-Term Care Facilities'
  | 'Medical Appliances & Equipment'
  | 'Medical Care'
  | 'Medical Care Facilities'
  | 'Medical Devices'
  | 'Medical Distribution'
  | 'Medical Instruments & Supplies'
  | 'Medical Laboratories & Research'
  | 'Medical Practitioners'
  | 'Pharmaceutical Retailers'
  | 'Specialized Health Services'
  | 'Aerospace/Defense - Major Diversified'
  | 'Aerospace/Defense Products & Services'
  | 'Cement'
  | 'Diversified Machinery'
  | 'Farm & Construction Machinery'
  | 'General Building Materials'
  | 'General Contractors'
  | 'Heavy Construction'
  | 'Industrial Electrical Equipment'
  | 'Industrial Equipment & Components'
  | 'Lumber, Wood Production'
  | 'Machine Tools & Accessories'
  | 'Manufactured Housing'
  | 'Metal Fabrication'
  | 'Pollution & Treatment Controls'
  | 'Residential Construction'
  | 'Small Tools & Accessories'
  | 'Textile Industrial'
  | 'Waste Management'
  | 'Aerospace & Defense'
  | 'Airlines'
  | 'Airports & Air Services'
  | 'Building Products & Equipment'
  | 'Business Equipment'
  | 'Business Equipment & Supplies'
  | 'Business Services'
  | 'Conglomerates'
  | 'Consulting Services'
  | 'Diversified Industrials'
  | 'Electrical Equipment & Parts'
  | 'Engineering & Construction'
  | 'Farm & Construction Equipment'
  | 'Farm & Heavy Construction Machinery'
  | 'Industrial Distribution'
  | 'Infrastructure Operations'
  | 'Integrated Freight & Logistics'
  | 'Integrated Shipping & Logistics'
  | 'Marine Shipping'
  | 'Metal Fabrication'
  | 'Pollution & Treatment Controls'
  | 'Railroads'
  | 'Rental & Leasing Services'
  | 'Security & Protection Services'
  | 'Shipping & Ports'
  | 'Specialty Business Services'
  | 'Specialty Industrial Machinery'
  | 'Staffing & Employment Services'
  | 'Staffing & Outsourcing Services'
  | 'Tools & Accessories'
  | 'Truck Manufacturing'
  | 'Trucking'
  | 'Waste Management'
  | 'Other'
  | 'Real Estate - General'
  | 'Real Estate Services'
  | 'Real Estate-Development'
  | 'Real Estate-Diversified'
  | 'REIT - Diversified'
  | 'REIT - Healthcare Facilities'
  | 'REIT - Hotel & Motel'
  | 'REIT - Industrial'
  | 'REIT - Office'
  | 'REIT - Residential'
  | 'REIT - Retail'
  | 'REIT-Diversified'
  | 'REIT-Healthcare Facilities'
  | 'REIT-Hotel & Motel'
  | 'REIT-Industrial'
  | 'REIT-Mortgage'
  | 'REIT-Office'
  | 'REIT-Residential'
  | 'REIT-Retail'
  | 'REIT-Specialty'
  | 'Advertising Agencies'
  | 'Air Delivery & Freight Services'
  | 'Air Services, Other'
  | 'Apparel Stores'
  | 'Auto Dealerships'
  | 'Auto Parts Stores'
  | 'Auto Parts Wholesale'
  | 'Basic Materials Wholesale'
  | 'Broadcasting - Radio'
  | 'Broadcasting - TV'
  | 'Building Materials Wholesale'
  | 'Business Services'
  | 'Catalog & Mail Order Houses'
  | 'CATV Systems'
  | 'Computers Wholesale'
  | 'Consumer Services'
  | 'Department Stores'
  | 'Discount, Variety Stores'
  | 'Drug Stores'
  | 'Drugs Wholesale'
  | 'Education & Training Services'
  | 'Electronics Stores'
  | 'Electronics Wholesale'
  | 'Entertainment - Diversified'
  | 'Food Wholesale'
  | 'Gaming Activities'
  | 'General Entertainment'
  | 'Grocery Stores'
  | 'Home Furnishing Stores'
  | 'Home Improvement Stores'
  | 'Industrial Equipment Wholesale'
  | 'Information Technology Services'
  | 'Jewelry Stores'
  | 'Lodging'
  | 'Major Airlines'
  | 'Management Services'
  | 'Marketing Services'
  | 'Medical Equipment Wholesale'
  | 'Movie Production, Theaters'
  | 'Music & Video Stores'
  | 'Personal Services'
  | 'Publishing - Books'
  | 'Publishing - Newspapers'
  | 'Publishing - Periodicals'
  | 'Railroads'
  | 'Regional Airlines'
  | 'Rental & Leasing Services'
  | 'Research Services'
  | 'Resorts & Casinos'
  | 'Restaurants'
  | 'Security & Protection Services'
  | 'Shipping'
  | 'Specialty Eateries'
  | 'Specialty Retail, Other'
  | 'Sporting Activities'
  | 'Sporting Goods Stores'
  | 'Staffing & Outsourcing Services'
  | 'Technical Services'
  | 'Toy & Hobby Stores'
  | 'Trucking'
  | 'Wholesale, Other'
  | 'Application Software'
  | 'Business Software & Services'
  | 'Communication Equipment'
  | 'Computer Based Systems'
  | 'Computer Distribution'
  | 'Computer Hardware'
  | 'Computer Peripherals'
  | 'Computer Systems'
  | 'Consumer Electronics'
  | 'Contract Manufacturers'
  | 'Data Storage'
  | 'Data Storage Devices'
  | 'Diversified Communication Services'
  | 'Diversified Computer Systems'
  | 'Diversified Electronics'
  | 'Electronic Components'
  | 'Electronic Gaming & Multimedia'
  | 'Electronics & Computer Distribution'
  | 'Electronics Distribution'
  | 'Health Information Services'
  | 'Healthcare Information Services'
  | 'Information & Delivery Services'
  | 'Information Technology Services'
  | 'Internet Content & Information'
  | 'Internet Information Providers'
  | 'Internet Service Providers'
  | 'Internet Software & Services'
  | 'Long Distance Carriers'
  | 'Multimedia & Graphics Software'
  | 'Networking & Communication Devices'
  | 'Personal Computers'
  | 'Printed Circuit Boards'
  | 'Processing Systems & Products'
  | 'Scientific & Technical Instruments'
  | 'Security Software & Services'
  | 'Semiconductor - Broad Line'
  | 'Semiconductor - Integrated Circuits'
  | 'Semiconductor - Specialized'
  | 'Semiconductor Equipment & Materials'
  | 'Semiconductor Memory'
  | 'Semiconductor- Memory Chips'
  | 'Semiconductors'
  | 'Software - Application'
  | 'Software - Infrastructure'
  | 'Software-Application'
  | 'Software-Infrastructure'
  | 'Solar'
  | 'Technical & System Software'
  | 'Telecom Services - Domestic'
  | 'Telecom Services - Foreign'
  | 'Wireless Communications'
  | 'Diversified Utilities'
  | 'Electric Utilities'
  | 'Foreign Utilities'
  | 'Gas Utilities'
  | 'Utilities - Diversified'
  | 'Utilities - Independent Power Producers'
  | 'Utilities - Regulated Electric'
  | 'Utilities - Regulated Gas'
  | 'Utilities - Regulated Water'
  | 'Utilities-Diversified'
  | 'Utilities-Independent Power Producers'
  | 'Utilities-Regulated Electric'
  | 'Utilities-Regulated Gas'
  | 'Utilities-Regulated Water'
  | 'Utilities-Renewable'
  | 'Water Utilities'

export type EHDIPODealType = 'Priced' | 'Expected'

export type EHDLIBORPeriod = '1W' | '1M' | '2M' | '3M' | '6M' | '12M'

export type EHDLIBORNomination = 'USD' | 'EUR' | 'GBP' | 'JPY'

export type EHDMacroEconomicIndicatorType =
  | 'population_total'
  | 'population_growth_annual'
  | 'inflation_consumer_prices_annual'
  | 'gdp_current_usd'
  | 'gdp_per_capita_usd'
  | 'gdp_growth_annual'
  | 'inflation_gdp_deflator_annual'
  | 'agriculture_value_added_percent_gdp'
  | 'industry_value_added_percent_gdp'
  | 'services_value_added_percent_gdp'
  | 'exports_of_goods_services_percent_gdp'
  | 'imports_of_goods_services_percent_gdp'
  | 'gross_capital_formation_percent_gdp'
  | 'net_migration'
  | 'gni_usd'
  | 'gni_per_capita_usd'
  | 'gni_ppp_usd'
  | 'gni_per_capita_ppp_usd'
  | 'income_share_lowest_twenty'
  | 'life_expectancy'
  | 'fertility_rate'
  | 'prevalence_hiv_total'
  | 'co2_emissions_tons_per_capita'
  | 'surface_area_km'
  | 'poverty_poverty_lines_percent_population'
  | 'revenue_excluding_grants_percent_gdp'
  | 'cash_surplus_deficit_percent_gdp'
  | 'startup_procedures_register'
  | 'market_cap_domestic_companies_percent_gdp'
  | 'mobile_subscriptions_per_hundred'
  | 'internet_users_per_hundred'
  | 'high_technology_exports_percent_total'
  | 'merchandise_trade_percent_gdp'
  | 'total_debt_service_percent_gni'

export type EHDMarketCapCategory =
  | 'Giant'
  | 'Large'
  | 'Medium'
  | 'Small'
  | 'Micro'

export type EHDNorgesBankAvailableCurrency =
  | 'GBP'
  | 'JPY'
  | 'USD'
  | 'EUR'
  | 'SEK'

export type EHDOptionContractSize = 'REGULAR'

export type EHDOptionType = 'CALL' | 'PUT'

export type EHDPaymentMethod = 'PayPal' | 'Stripe'

export type EHDPeriod = 'Annual' | 'Quarterly'

export type EHDSector =
  | 'Basic Materials'
  | 'Consumer Cyclical'
  | 'Financial Services'
  | 'Real Estate'
  | 'Consumer Defensive'
  | 'Healthcare'
  | 'Utilities'
  | 'Communication Services'
  | 'Energy'
  | 'Industrials'
  | 'Technology'
  | 'Other'

export type EHDSubscriptionType = 'monthly' | 'yearly'

export type EHDSymbolType =
  | 'Common Stock'
  | 'Currency'
  | 'ETF'
  | 'FUND'
  | 'BOND'
  | 'MONEY'
  | 'INDEX'

export type EHDScreenerOperation =
  | '='
  | 'in'
  | 'not in'
  | 'match'
  | '>'
  | '<'
  | '>='
  | '<='
  | '!='

export type EHDScreenerSignal =
  | '50d_new_lo'
  | '50d_new_hi'
  | '200d_new_lo'
  | '200d_new_hi'
  | 'bookvalue_neg'
  | 'bookvalue_pos'
  | 'wallstreet_lo'
  | 'wallstreet_hi'

export type EHDScreenerFilter =
  | 'code'
  | 'name'
  | 'exchange'
  | 'sector'
  | 'industry'
  | 'market_capitalization'
  | 'earnings_share'
  | 'dividend_yield'
  | 'refund_1d_p'

export type EHDScreenerSortKey =
  | 'market_capitalization'
  | 'earnings_share'
  | 'dividend_yield'

export type EHDSTIBORPeriod = '1W' | '1M' | '2M' | '3M' | '6M'
